<a href="https://colab.research.google.com/github/aaravpathak9984-boop/Python_class_lec/blob/main/Ds_Lec4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## ***Numpy***

In [ ]:
!pip install numpy

import numpy as np


In [ ]:
a=np.array([3,3,3,3.8,'hello',False])

print(bool(a[-1]))

a=False
print(bool(a))

True
False


### Some imp funcitons in numpy

#### np.zeros(dimension of array)

#### arr_1d = np.array([1, 2, 3, 4])
#### arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Built-in initializers
#### zeros  = np.zeros((2, 3))        # 2x3 matrix filled with 0.0
#### ones   = np.ones((3, 3))         # 3x3 matrix filled with 1.0
#### const  = np.full((2, 2), 7)      # 2x2 matrix filled with 7
i#### den   = np.eye(3)               # 3x3 Identity matrix

# Ranged values
#### seq    = np.arange(0, 10, 2)     # [0, 2, 4, 6, 8]
#### lin    = np.linspace(0, 1, 5)    # 5 evenly spaced points: [0.,0.25,0.5 ,0.75,1.  ]


In [ ]:
## zeros filled vector

a1=np.zeros((3,4,3),dtype=int)
print(type(a1[0][0][0]))


## ones filled vector

a2=np.ones((2,3,4),dtype=int)
print(a2)

<class 'numpy.int64'>
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [ ]:
### np.empty - > gives you garbage values the amnt you mentoned

a3=np.empty(4,dtype=int)
print(a3)

[0 0 0 0]


In [ ]:
## np.full -> gives you array with same elements

a4=np.full((3,3),5,dtype=int)
print(a4)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
## array arrange

a5=np.arange(4,12,2)
print(a5)


[ 4  6  8 10]


In [ ]:
## array linspace

a6=np.linspace(2,12,4,dtype=int,endpoint=False)
print(a6)

[2 4 7 9]


#### array inspection

#### shape

#### size

#### dtype

In [ ]:
a7=np.array([[1,2,3],[4,5,6],[7,8,9]])


print(a7.shape)
print(a7.size)
print(a7.dtype)

# import random

# print(random.randint(1,5,4))
# print(np.random.choice(a7, (3, 4)))

print(np.random.randint(1,5,(2,4)))
# print(np.random.choice(a7))

(3, 3)
9
int64
[[3 4 3 4]
 [1 4 1 3]]


## broadcasting of vectors

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
brr=np.array([[11,12,13],[22,23,24]])

print(arr*2 ,'\n')
print(arr+brr,'\n')
print(arr*brr,'\n')



print(([1,2,3,4]+[4,5,6])*2) # gives two times the same list that's why array is used

[[ 2  4  6]
 [ 8 10 12]] 

[[12 14 16]
 [26 28 30]] 

[[ 11  24  39]
 [ 88 115 144]] 

[1, 2, 3, 4, 4, 5, 6, 1, 2, 3, 4, 4, 5, 6]


#### some important funcitons


In [ ]:
# 1. Generates 6 random integers from 1 (inclusive) to 12 (exclusive)
# Result: A 1D array of shape (6,) e.g., [5, 2, 11, 7, 1, 9]
arr2 = np.random.randint(1, 12, 6)

# 2. Prints the 1D random array followed by a blank new line (\n)
print(arr2, '\n')

## if we need to convert into matrix

# 3. Reshapes the 6-element array into a 2D matrix of 3 rows and 2 columns
# Your comment is correct: (3,3) fails because it needs 9 elements, but we only have 6
brr2 = arr2.reshape((3, 2))

# 4. Reshapes the same 6-element array into a 2D matrix of 2 rows and 3 columns
brr3 = arr2.reshape((2, 3))

# 5. Prints the 3x2 matrix followed by a blank line
print(brr2, '\n')

# 6. Prints the 2x3 matrix followed by a blank line
print(brr3, '\n')

# 7. Transposes brr2 (flips its rows into columns and columns into rows)
# Since brr2 was (3, 2), at2 becomes a matrix of shape (2, 3)
at2 = brr2.transpose()

# 8. Prints the transposed 2x3 matrix followed by a blank line
print(at2, '\n')

# 9. Concatenates (joins) brr3 and at2 horizontally along the columns (axis=1)
# Both matrices are shape (2, 3). Joining them side-by-side creates a shape of (2, 6)
ac2 = np.concatenate((brr3, at2), axis=1)

# 10. Prints the final horizontally stacked 2x6 matrix
print(ac2)


[7 3 6 9 1 9] 

[[7 3]
 [6 9]
 [1 9]] 

[[7 3 6]
 [9 1 9]] 

[[7 6 1]
 [3 9 9]] 

[[7 3 6 7 6 1]
 [9 1 9 3 9 9]]


In [ ]:
a=np.random.randint(1,11,5)
b=np.random.randint(1,20,5)
c=np.where((b>11),b,a)

print(a,'\n')
print(b,'\n')
print(c,'\n')

print(sum(a),min(a),max(a),'\n')

a.sort()

print(a,np.unique(a),np.matmul(a,b))




[9 3 6 5 3] 

[16 13 16  2  5] 

[16 13 16  5  3] 

26 3 9 

[3 3 5 6 9] [3 5 6 9] 224


## problem of cricket scorer

In [ ]:
sc=[]

days=np.array(['monday','tuesday','wednesday','thursday','friday','saturday','sunday'])
for i in range(7):
  x=int(input(f'Enter the score of player on {days[i]}: 1'))
  sc.append(x)

scores=np.array(sc)

print(scores)





for i in range(7):

  print(f'on {days[i]} he scored : {scores[i]}')

min_idx = np.argmin(scores)
max_idx = np.argmax(scores)



print(f'the minimum score of player is {scores.min()} on {days[min_idx]}')
print(f'the maximum score of player is {max(scores)} on {days[max_idx]}')
print(f'the average score of player is {np.mean(scores)}')
print(f'the total score of player is {np.sum(scores)}')
print(f'the median score of player is {np.median(scores)}')
print(f'the standard deviation of player is {np.std(scores)}')



Enter the score of player on monday: 12
Enter the score of player on tuesday: 23
Enter the score of player on wednesday: 42
Enter the score of player on thursday: 21
Enter the score of player on friday: 100
Enter the score of player on saturday: 200
Enter the score of player on sunday: 00
[ 12  23  42  21 100 200   0]
on monday he scored : 12
on tuesday he scored : 23
on wednesday he scored : 42
on thursday he scored : 21
on friday he scored : 100
on saturday he scored : 200
on sunday he scored : 0
the minimum score of player is 0 on sunday
the maximum score of player is 200 on saturday
the average score of player is 56.857142857142854
the total score of player is 398
the median score of player is 23.0
the standard deviation of player is 65.7363317057048


In [ ]:
pa=np.array([1,2,3,4])
b=pa.copy()
b[0]=5
print(pa,b)

[1 2 3 4] [5 2 3 4]
