<a href="https://colab.research.google.com/github/aaravpathak9984-boop/Python_class_lec/blob/main/Ds_Lec5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

####question
### create a matrix of 5X5

### mean of values rows and columns wise

### replace all even num with -1

##sort arrray row and column wise

### sum column wise and row wise sep

#### no. of -ve in each col

In [ ]:
# To create random matrix of 5 X 5

ma=np.random.randint(1,90,25)
matrix=ma.reshape((5,5))

print(f"The matrix is: \n {matrix} \n")

# Finding mean row wise:
mn_row=np.mean(matrix,axis=1)
print(f"The means of matrix row wise is : {mn_row} \n")

# Finding mean col wise:
mn_col=np.mean(matrix,axis=0)
print(f"The means of matrix col wise is : {mn_col} \n")


# To replace where ever we get even just replace is with -1
matrix=np.where(matrix%2==0,-1,matrix)

print(f"The matrix with replaced evens are: \n {matrix} \n")



# To sort col wise:
matrix.sort(axis=0)

# To sort row wise:
matrix.sort(axis=1)


# To find sum of rows

sum_row=np.sum(matrix,axis=1)

print(f"The sum of row wise is : \n {sum_row} \n")

#to find sum of cols:
sum_col=np.sum(matrix,axis=0)
print(f"The sum of col wise is : \n {sum_col} \n")

# to find count of total count of -1

cnt=sum(np.sum(matrix==-1,axis=0))

# can also do like:

cnt1=np.sum(np.where(matrix==-1,1,0))
print(f" The total count of -1 : \n{cnt} : {cnt1} \n")




The matrix is: 
 [[83 19  5 26 13]
 [32 22 40 74  7]
 [20 58 39 79 54]
 [36  9 10 56 76]
 [50 30 59 12  5]] 

The means of matrix row wise is : [29.2 35.  50.  37.4 31.2] 

The means of matrix col wise is : [44.2 27.6 30.6 49.4 31. ] 

The matrix with replaced evens are: 
 [[83 19  5 -1 13]
 [-1 -1 -1 -1  7]
 [-1 -1 39 79 -1]
 [-1  9 -1 -1 -1]
 [-1 -1 59 -1  5]] 

The sum of row wise is : 
 [ -5  -5   7  53 253] 

The sum of col wise is : 
 [  9  15  63  91 125] 

 The total count of -1 : 
15 : 15 



### question 2

### 5X5 matrix of stock, and demand

### remaning stocks

### -ve values with 0

In [ ]:
st=np.random.randint(1,50,25)
dm=np.random.randint(1,50,25)


#stocks=st.reshape((5,5))

# can also do like:
stocks=np.random.randint(1,50,(5,5))
print(f"The stocks matrix is: \n {stocks} \n")
demand=dm.reshape((5,5))

print(f"The stocks matrix is: \n {demand} \n")



rem_stocks=stocks-demand

print(f"The remaining stocks are: \n{rem_stocks}\n")

posi_stocks=np.copy(rem_stocks)
posi_stocks[posi_stocks<0]=0

print(f"The remaining stocks are: \n{posi_stocks}\n")


# Total shortage

total_shor_days=np.sum(rem_stocks<0,axis=0)

print(f"The total no. of products the have shortages days wise are : \n{total_shor_days}\n")


total_shor_col=np.sum(np.where(rem_stocks<0,rem_stocks,0), axis=0)
print(f"The total no. of shortage in day wise is : {-1*total_shor_col}\n")


total_shortage=np.sum(total_shor_col)
print(f"The total shortage is : {-1*total_shortage}\n")




#products with zeros stokcs are

pord_zero_stock=np.sum(np.where(posi_stocks==0,1,0))

print(f"The products with zero stocks are: \n{pord_zero_stock}\n")

##sorting column wise

posi_stocks.sort(axis=0)

print(f"The sorted col wise are: \n{posi_stocks}\n")


The stocks matrix is: 
 [[43 49 40 42 28]
 [ 8 47 31  5 40]
 [ 9 32 41 46 41]
 [38  5  8 47 33]
 [43 27 31  9 35]] 

The stocks matrix is: 
 [[24  8 43 41 35]
 [22 36 38 14 49]
 [35 42 37 25 23]
 [17 45 25  2 35]
 [49 10 35 39 25]] 

The remaining stocks are: 
[[ 19  41  -3   1  -7]
 [-14  11  -7  -9  -9]
 [-26 -10   4  21  18]
 [ 21 -40 -17  45  -2]
 [ -6  17  -4 -30  10]]

The remaining stocks are: 
[[19 41  0  1  0]
 [ 0 11  0  0  0]
 [ 0  0  4 21 18]
 [21  0  0 45  0]
 [ 0 17  0  0 10]]

The total no. of products the have shortages days wise are : 
[3 2 4 2 3]

The total no. of shortage in day wise is : [46 50 31 39 18]

The total shortage is : 184

The products with zero stocks are: 
14

The sorted col wise are: 
[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0 11  0  1  0]
 [19 17  0 21 10]
 [21 41  4 45 18]]



# ****Pandas****

In [63]:
!pip install pandas
import pandas as pd

In [69]:
file_=pd.read_csv("student_data.csv",sep=',')

print(file_.head(3)) # to get the data of first 3 rows by default is 5

print(file_.tail(5)) # to get the data from last 5 rows by defailt is 5

   study_hours  attendance  sleep_hours  internet_usage  \
0            7          56            8               7   
1            4          69            5               3   
2           11          60            7               6   

   assignments_completed  previous_score  exam_score placement_status  
0                     10              62       100.0           Placed  
1                      8              56       100.0           Placed  
2                     10              45       100.0           Placed  
      study_hours  attendance  sleep_hours  internet_usage  \
9995            2          58            9               7   
9996            7          98            6               9   
9997           10          44            8               5   
9998           10          75            7               5   
9999            2          70            6              11   

      assignments_completed  previous_score  exam_score placement_status  
9995                      8